'use strict';
/* 不載入第三方程式；顯示值與作圖值分離，避免製造精確假象。 */
const GuideCore = (() => {
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm = value => String(value ?? '').normalize('NFKC').toLocaleLowerCase('zh-Hant').trim();
  const search = (profiles, query, family) => profiles.filter(p => (!family || p.family === family) && norm(JSON.stringify(p)).includes(norm(query)));
  const percent = value => Number.isFinite(value) ? Math.min(100,Math.max(0,value)) : 0;
  const route = hash => { const raw=hash.replace(/^#/,''); if(raw.startsWith('religion/')) {try{return {profile:decodeURIComponent(raw.slice(9))};}catch{return {profile:null};}} return {section:raw||'home'}; };
  return {escape,norm,search,percent,route};
})();
if(typeof module !== 'undefined') module.exports=GuideCore;
if(typeof document !== 'undefined') (() => {
const D=window.GUIDE_DATA, E=GuideCore.escape, $=s=>document.querySelector(s);
if(!D){ $('#no-results').hidden=false;$('#no-results').innerHTML='<h3>資料未能載入</h3><p>請重新整理，或使用頁尾的完整資料下載連結。</p>';$('#results-status').textContent='資料未能載入'; return; }
const profiles=D.profiles.profiles, dem=D.demographics, local=D.taiwanSafety;
const sources=D.sources, sourceMap=new Map(sources.map((s,i)=>[s.id,{...s,number:i+1}]));
const colors=['#e7b958','#82b6a6','#acb5cc','#d99071','#a8bd71','#aa92bc','#f0d8a6'];
const cite=(ids=[])=>'<span class="cite">'+ids.map(id=>{const s=sourceMap.get(id);return s?`<a href="${E(s.url)}" target="_blank" rel="noopener noreferrer" title="${E(s.title)}" aria-label="來源 ${s.number}：${E(s.title)}">[${s.number}] ↗</a>`:'';}).join(' ')+'</span>';
const urlCite=url=>cite(sources.filter(s=>s.url===url).map(s=>s.id));
const fact=f=>`<p>${E(f.text)}${cite(f.sourceIds)}</p>${f.caveat?`<p class="small-note"><strong>讀資料提醒：</strong>${E(f.caveat)}</p>`:''}`;
const list=(items,fn)=>items.map(fn).join('');
let lastFocused=null, profileFromUI=false, closingPending=false;
function renderProfiles(){const hits=GuideCore.search(profiles,$('#search').value,$('#family').value);$('#profile-grid').innerHTML=list(hits,p=>`<article class="profile-card"><div class="card-motif" style="--card-bg:${['#e4ede5','#f1e5cc','#e5e7ee','#f2e1d6'][profiles.indexOf(p)%4]}"><span class="card-number">${String(profiles.indexOf(p)+1).padStart(2,'0')}</span></div><div class="card-body"><span class="family-label">${E(p.family)}</span><h3>${E(p.name)}</h3><p class="card-description">${E(p.summary)}</p><p class="small-note">${cite(p.summarySourceIds)}</p><button class="read" data-profile="${E(p.id)}" aria-label="深入認識${E(p.name)}">閱讀探索筆記 <span aria-hidden="true">↗</span></button></div></article>`);$('#profile-count').textContent=`${hits.length} / ${profiles.length} 個探索主題`;$('#results-status').textContent=`找到 ${hits.length} 個主題`;$('#no-results').hidden=hits.length!==0;}
$('#family').innerHTML+=[...new Set(profiles.map(p=>p.family))].map(x=>`<option>${E(x)}</option>`).join('');
$('#search').addEventListener('input',renderProfiles);$('#family').addEventListener('change',renderProfiles);$('#search-form').addEventListener('submit',e=>e.preventDefault());$('#search-form').addEventListener('reset',e=>{e.preventDefault();$('#search').value='';$('#family').value='';renderProfiles();$('#search').focus();});
$('#profile-grid').addEventListener('click',e=>{const b=e.target.closest('[data-profile]');if(b){lastFocused=b;profileFromUI=true;location.hash='religion/'+encodeURIComponent(b.dataset.profile);}});
function renderDetail(p){$('#detail').innerHTML=`<p class="eyebrow">${E(p.family)}</p><h2 id="detail-title">${E(p.name)}</h2><p class="detail-intro">${E(p.summary)}${cite(p.summarySourceIds)}</p><div class="detail-actions"><button id="copy-link" class="button secondary">複製這頁連結</button><span class="copy-status" id="copy-status" role="status"></span></div><h3>從哪裡開始？</h3>${fact(p.origin)}<h3>歷史的幾個座標</h3><ol class="timeline">${list(p.history,h=>`<li><strong>${E(h.date)}</strong>${fact(h)}</li>`)}</ol><h3>信仰與日常</h3>${list(p.features,f=>`<h4>${E(f.label)}</h4>${fact(f)}`)}<div class="note"><h4>同一傳統裡的多樣性</h4>${fact(p.diversity)}</div><h3>打開一個常見誤解</h3>${list(p.misconceptions,m=>`<h4>${E(m.misconception)}</h4><p>${E(m.correction)}${cite(m.sourceIds)}</p>`)}<h3>可以討論的歷史與爭議</h3>${list(p.contentions,c=>`<h4>${E(c.title)}</h4>${fact(c)}`)}<div class="note"><h4>帶著問題繼續讀</h4><ul>${list(p.questions,q=>`<li>${E(q)}</li>`)}</ul><p class="small-note">討論提示，沒有預設標準立場；可用上方來源查核與延伸。</p></div>`;$('#copy-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);$('#copy-status').textContent='連結已複製';}catch{$('#copy-status').textContent='請從瀏覽器網址列複製本頁連結。';}});}
function closeDialog(){if(!$('#profile-dialog').open||closingPending)return;closingPending=true;if(profileFromUI){history.back();}else{history.replaceState(null,'',location.pathname+location.search+'#explore');syncRoute();}}
function syncRoute(){closingPending=false;const r=GuideCore.route(location.hash),p=profiles.find(p=>p.id===r.profile);if(p){renderDetail(p);if(!$('#profile-dialog').open)$('#profile-dialog').showModal();$('#profile-dialog').scrollTop=0;document.body.classList.add('dialog-open');$('#close-dialog').focus();}else{if($('#profile-dialog').open)$('#profile-dialog').close();document.body.classList.remove('dialog-open');if(lastFocused&&lastFocused.isConnected){lastFocused.focus({preventScroll:true});lastFocused=null;}if(r.profile){history.replaceState(null,'',location.pathname+location.search+'#explore');$('#explore').scrollIntoView();}}}
$('#close-dialog').addEventListener('click',closeDialog);$('#profile-dialog').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});$('#profile-dialog').addEventListener('click',e=>{if(e.target===$('#profile-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});window.addEventListener('hashchange',syncRoute);
let offset=0;const circumference=2*Math.PI*80;
const segments=dem.global.values.map((v,i)=>{const length=GuideCore.percent(v.pct)*circumference/100;const s=`<circle cx="110" cy="110" r="80" fill="none" stroke="${colors[i]}" stroke-width="28" stroke-dasharray="${length} ${circumference-length}" stroke-dashoffset="${-offset}"/>`;offset+=length;return s;}).join('');
$('#global-data').innerHTML=`<div class="global-panel"><div class="ring-wrap"><svg viewBox="0 0 220 220" aria-hidden="true">${segments}</svg><div class="ring-label"><strong>2020</strong><span>全球宗教認同估計</span></div></div><div><div class="legend" role="list" aria-label="2020年全球宗教認同分布">${list(dem.global.values,(v,i)=>`<div class="legend-row" role="listitem"><span class="swatch" style="--swatch:${colors[i]}"></span><span>${E(v.label)}<small class="count-hint">約 ${E(v.countDisplay)} 人</small></span><strong>${E(v.pctDisplay)}</strong></div>`)}</div><p class="chart-caption">資料年：2020；研究發布：2025-06-09。Pew Research Center${cite(['pew-composition'])}<br>百分比與人數均為估計；顯示值經四捨五入。</p></div></div><p class="chart-caption">「其他宗教」合併多種傳統；未單列不是零。「無宗教歸屬」也不等於沒有任何信仰或儀式。${cite(['pew-method'])}</p>`;
const opts=list(dem.countries,c=>`<option value="${E(c.countryCode)}">${E(c.name)}</option>`);$('#country').innerHTML=opts;$('#country-b').innerHTML=opts;$('#country-b').selectedIndex=Math.min(1,dem.countries.length-1);
function renderCountry(select,target){const c=dem.countries.find(c=>c.countryCode===$(select).value);$(target).innerHTML=`<article class="country-box"><h4>${E(c.name)} <small>2020</small></h4>${list(c.values,(v,i)=>`<div class="bar-row"><span>${E(v.label)}</span><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="--value:${GuideCore.percent(v.pct)}%;--swatch:${colors[i]}"></div></div><strong>${E(v.pctDisplay)}</strong></div>`)}<p class="chart-caption">人口估計：約 ${E(c.populationDisplay)} 人。${cite(['pew-composition'])}</p><p class="chart-caption">讀圖問題：${E(c.teachingPrompt)}</p></article>`;}
$('#country').addEventListener('change',()=>renderCountry('#country','#country-data'));$('#country-b').addEventListener('change',()=>renderCountry('#country-b','#country-data-b'));
$('#demographic-method').innerHTML=`<p>${E(dem.meta.coverage)}${cite(['pew-method'])}</p><p>${E(dem.meta.estimateType)} ${E(dem.meta.versionNote)}${cite(['pew-composition'])}</p>${list(dem.methodNotes,m=>`<h4>${E(m.title)}</h4><p>${E(m.text)}${urlCite(m.sourceUrl)}</p>`)}<p>${E(dem.meta.displayNote)}</p><p>選錄 ${dem.countries.length} 個國家／地區，並非世界完整名單；完整資料請見來源。本站長條採0–100%的固定尺度，極小比例可能難以看見，請以數字標籤為準。</p>`;
const section=id=>local.sections.find(s=>s.id===id);
const tw=section('taiwan');$('#taiwan-content').innerHTML=`<div class="note"><p>${E(tw.intro)}</p><p>本區2023年成人調查，與上方2020年全人口估計的年份、母體及分類不同，請勿直接相減當成趨勢。${cite(['tw-pew-method','pew-method'])}</p></div><div class="content-grid">${list(tw.facts,f=>`<article class="info-card" id="${E(f.id)}"><h3>${E(f.title)}</h3>${fact(f)}${f.data?`<div class="survey-bars" aria-label="2023年臺灣成年人宗教認同百分比">${list(f.data,v=>`<div class="bar-row"><span>${E(v.label)}</span><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="--value:${GuideCore.percent(v.value)}%;--swatch:#588877"></div></div><strong>${v.value}%</strong></div>`)}</div><p class="small-note">上述顯示值合計98%，不補造剩餘類別；請見本卡調查限制。</p>`:''}</article>`)}</div>`;
const glossary=D.profiles.glossary||[];const nonreligion=D.profiles.nonreligion;$('#concept-grid').innerHTML=`<details class="concept-card"><summary>${E(nonreligion.name)}</summary>${fact(nonreligion)}</details>`+list(glossary,g=>`<details class="concept-card"><summary>${E(g.term)}</summary><p>${E(g.definition)}${cite(g.sourceIds)}</p></details>`)+list(section('terms').facts,f=>`<details class="concept-card"><summary>${E(f.title)}</summary>${fact(f)}</details>`);
const warning=section('warning-signs'),cases=section('cases'),help=section('help');$('#safety-content').innerHTML=`<div class="safety-banner"><span class="symbol" aria-hidden="true">↗</span><div><h3>你有提問、拒絕與求助的權利</h3><p>${E(warning.intro)}${cite(['safe-miviludes'])}</p></div></div><ul class="safety-list">${list(warning.facts,f=>`<li><h4>${E(f.title)}</h4>${fact(f)}</li>`)}</ul><h3 class="section-subtitle">${E(cases.title)}</h3><p>${E(cases.intro)}</p>${list(cases.facts,f=>`<article class="case-card"><h3>${E(f.title)}</h3>${fact(f)}</article>`)}<h3 class="section-subtitle">${E(help.title)}</h3><div class="content-grid">${list(help.facts,f=>`<article class="info-card"><h3>${E(f.title)}</h3>${fact(f)}</article>`)}</div>`;
const types=[...new Set(sources.map(s=>s.type))];$('#source-type').innerHTML+=types.map(t=>`<option>${E(t)}</option>`).join('');function renderSources(){const s=sources.filter(s=>!$('#source-type').value||s.type===$('#source-type').value);$('#source-list').innerHTML=list(s,source=>{const n=sourceMap.get(source.id).number;return `<article class="source-list-item" id="source-${E(source.id)}"><span class="source-id">${String(n).padStart(2,'0')}</span><div><a href="${E(source.url)}" target="_blank" rel="noopener noreferrer">${E(source.title)} ↗</a><p class="source-meta"><span class="pill">${E(source.type)}</span>${E(source.producer||source.publisher||'')} · 發布：${E(source.publishedDate||source.publishedAt||'頁面未標明')} · 查閱：${E(source.accessedAt||source.accessedDate||D.updatedAt)}</p>${source.note?`<p>${E(source.note)}</p>`:''}${source.alternateUrl?`<p><a href="${E(source.alternateUrl)}" target="_blank" rel="noopener noreferrer">同機關 PDF 備用閱讀 ↗</a></p>`:''}</div></article>`;});$('#source-count').textContent=`顯示 ${s.length} / ${sources.length} 筆來源`;}
$('#source-type').addEventListener('change',renderSources);$('#editorial').innerHTML=`<p>內容查核日期：${E(D.updatedAt)}。${E(D.profiles.editorialNote||'')}</p><p>宗教卡片按來源整理起源、特色、內部多樣性與爭議；題目與導讀屬編輯提示。國別數據是研究估計，不是即時統計。來源類型依製作者與內容用途人工標示，不依網域尾碼判定。</p><p>研究機構資料適合觀察統計與方法；宗教團體自述適合理解其自我描述，不能代替獨立評估；政府資料呈現法律、政策或案件紀錄，也有其管轄範圍與時間限制。</p>`;
document.querySelectorAll('.intro-grid article p').forEach((p,i)=>{p.innerHTML+=cite(i===0?['method']:i===1?['pew-method']:['method','udhr']);});
renderProfiles();renderCountry('#country','#country-data');renderCountry('#country-b','#country-data-b');renderSources();syncRoute();
})();
