'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.resolve(__dirname,'..');const data=JSON.parse(fs.readFileSync(path.join(root,'data/世界宗教導覽資料.json'),'utf8'));const core=require('../app.js');
let checks=0;const check=(name,fn)=>{fn();checks++;console.log('通過：'+name)};
check('來源識別碼唯一、HTTPS網址、類型齊備',()=>{const ids=data.sources.map(s=>s.id);assert.equal(ids.length,new Set(ids).size);for(const s of data.sources){assert.match(s.url,/^https:\/\//);assert.ok(s.type);assert.ok(s.title);}});
check('全部主張來源能對帳',()=>{const sources=new Set(data.sources.map(s=>s.id));function walk(x){if(!x||typeof x!=='object')return;for(const [k,v] of Object.entries(x)){if(k==='sourceIds'||k.endsWith('SourceIds'))for(const id of v)assert.ok(sources.has(id),'未知來源 '+id);else if(k==='sourceId')assert.ok(sources.has(v),'未知來源 '+v);else walk(v);}}walk(data);});
check('2020年七類全球與國別估計一致、總和合理',()=>{const d=data.demographics;assert.equal(d.meta.dataYear,2020);const ids=d.categories.map(c=>c.id).sort();for(const item of [d.global,...d.countries]){assert.equal(item.dataYear,2020);assert.deepEqual(item.values.map(v=>v.id).sort(),ids);const sum=item.values.reduce((a,v)=>a+v.pct,0);assert.ok(Math.abs(sum-100)<.02,`${item.name||'全球'}=${sum}`);for(const v of item.values){assert.equal(v.dataYear,2020);assert.ok(Number.isFinite(v.pct)&&v.pct>=0&&v.pct<=100);assert.ok(v.pctDisplay);assert.ok(v.countDisplay);if(v.pct>0&&v.pct<.1)assert.equal(v.pctDisplay,'<0.1%');}}});
check('台灣不同年份與98%顯示總和不造假',()=>{const tw=data.taiwanSafety.sections.find(s=>s.id==='taiwan').facts.find(f=>f.id==='tw-survey');assert.equal(tw.dataYear,2023);assert.equal(tw.data.reduce((a,b)=>a+b.value,0),98);assert.ok(tw.caveat.includes('18歲'));});
check('主題識別碼唯一且主要欄位有來源',()=>{const p=data.profiles.profiles;assert.ok(p.length>=10);assert.equal(new Set(p.map(p=>p.id)).size,p.length);for(const x of p){assert.ok(x.summarySourceIds.length);assert.ok(x.origin.sourceIds.length);assert.ok(x.diversity.sourceIds.length);for(const list of ['history','features','contentions','misconceptions']){assert.ok(x[list].length);for(const entry of x[list])assert.ok(entry.sourceIds.length);}}});
check('搜尋、類別與空值狀態',()=>{const p=data.profiles.profiles;assert.equal(core.search(p,'','').length,p.length);assert.ok(core.search(p,p[0].name,'').length);assert.equal(core.search(p,'這個字串不存在987654','').length,0);assert.ok(core.search(p,'',p[0].family).every(x=>x.family===p[0].family));assert.equal(core.search(p,'','不存在類別').length,0);});
check('深鏈、非法URI與HTML跳脫',()=>{assert.equal(core.route('#religion/buddhism').profile,'buddhism');assert.equal(core.route('#religion/%E0%A4%A').profile,null);assert.equal(core.route('#taiwan').section,'taiwan');assert.equal(core.escape('<script>'),'&lt;script&gt;');assert.equal(core.percent(null),0);assert.equal(core.percent(NaN),0);assert.equal(core.percent(101),100);assert.equal(core.percent(-1),0);});
check('所有本地資產路徑存在',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const [,url] of html.matchAll(/(?:src|href)="([^"#][^"]*)"/g)){if(/^https?:/.test(url))continue;assert.ok(fs.existsSync(path.join(root,url.split('?')[0])),url);}const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);assert.match(html,/lang="zh-Hant"/);assert.match(html,/name="viewport"/);});

check('JSON與網頁資料一致，沒有外部執行期依賴',()=>{const c={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'data/content.js'),'utf8'),c);assert.equal(JSON.stringify(c.window.GUIDE_DATA),JSON.stringify(data));const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.ok(!/<script[^>]+src="https?:/.test(html));assert.ok(!/<link[^>]+href="https?:/.test(html));});
check('瀏覽器邏輯：初始、搜尋、篩選、同步重設、開關詳情及無效深鏈',()=>{
 const els=new Map();class Element{constructor(id){this.id=id;this.value='';this.innerHTML='';this.textContent='';this.hidden=false;this.open=false;this.listeners={};this.isConnected=true;this.selectedIndex=0;}addEventListener(k,fn){this.listeners[k]=fn;}focus(){}scrollIntoView(){}showModal(){this.open=true;}close(){this.open=false;}set innerHTML(v){this._html=v;if(this.id==='country'||this.id==='country-b'){this.value=data.demographics.countries[0].countryCode;}}get innerHTML(){return this._html;}getBoundingClientRect(){return {left:0,right:800,top:0,bottom:900};}}
 const q=id=>{id=id.replace(/^#/,'');if(!els.has(id))els.set(id,new Element(id));return els.get(id);};const events={};const location={hash:'',pathname:'/student-world-religions/',search:'',href:'https://example.com/#home'};const context={window:{GUIDE_DATA:data,addEventListener:(k,fn)=>events[k]=fn},document:{querySelector:q,querySelectorAll:()=>[],body:{classList:{add(){},remove(){}}}},location,history:{replaceState(_,__,url){location.hash=url.includes('#')?'#'+url.split('#')[1]:'';},back(){location.hash='#explore';events.hashchange();}},navigator:{clipboard:{writeText:async()=>{}}},console};vm.runInNewContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),context);
 assert.ok(q('profile-grid').innerHTML.includes(data.profiles.profiles[0].name));assert.ok(q('global-data').innerHTML.includes('2020'));assert.ok(q('country-data').innerHTML.includes('2020'));assert.ok(q('source-list').innerHTML.includes(data.sources[0].title.replaceAll('&','&amp;')));
 q('search').value='不存在98765';q('search').listeners.input();assert.equal(q('no-results').hidden,false);q('search-form').listeners.reset({preventDefault(){}});assert.equal(q('search').value,'');assert.equal(q('family').value,'');assert.equal(q('no-results').hidden,true);
 q('family').value=data.profiles.profiles[0].family;q('family').listeners.change();assert.ok(q('profile-grid').innerHTML.includes(data.profiles.profiles[0].name));q('search-form').listeners.reset({preventDefault(){}});
 location.hash='#religion/'+data.profiles.profiles[0].id;events.hashchange();assert.equal(q('profile-dialog').open,true);assert.ok(q('detail').innerHTML.includes('歷史的幾個座標'));q('close-dialog').listeners.click();assert.equal(q('profile-dialog').open,false);assert.equal(location.hash,'#explore');
 location.hash='#religion/'+data.profiles.profiles[1].id;events.hashchange();q('profile-dialog').listeners.cancel({preventDefault(){}});assert.equal(q('profile-dialog').open,false);
 // UI 點擊會新增片段導航；關閉走 Back，Forward 應可再開啟。
 const button={dataset:{profile:data.profiles.profiles[0].id},isConnected:true,focus(){}};q('profile-grid').listeners.click({target:{closest(){return button;}}});events.hashchange();assert.equal(q('profile-dialog').open,true);q('close-dialog').listeners.click();assert.equal(q('profile-dialog').open,false);location.hash='#religion/'+data.profiles.profiles[0].id;events.hashchange();assert.equal(q('profile-dialog').open,true);location.hash='#taiwan';events.hashchange();assert.equal(q('profile-dialog').open,false);
 location.hash='#religion/not-a-profile';events.hashchange();assert.equal(location.hash,'#explore');assert.equal(q('profile-dialog').open,false);
 q('source-type').value=data.sources[0].type;q('source-type').listeners.change();assert.ok(q('source-count').textContent.includes('/'));q('source-type').value='';q('source-type').listeners.change();assert.ok(q('source-count').textContent.includes(String(data.sources.length)));
 });
console.log(`\n完成 ${checks} 組驗證。提醒：模擬DOM測試不取代真實瀏覽器的視覺與鍵盤檢查。`);
